resources:
  - kind: repository
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .name
          title: .name
          blueprint: '"repository"'
          properties:
            readme: file://README.md
            url: .html_url
            envs: file://environments.yaml
