  name: test
  on:
    workflow_dispatch:
      inputs:
        port_payload:
          required: true
          description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
          type: string
  jobs:
    search-entity:
      runs-on: ubuntu-latest
      outputs:
        entities: ${{ steps.test-action.outputs.entities }}
      steps:
        - id: test-action 
          uses: port-labs/port-github-action@v1
          with:
            clientId: ${{ secrets.PORT_CLIENT_ID }}
            clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
            operation: SEARCH
            query: |-
              {
              "combinator": "and",
              "rules": [
                  {
                      "property": "$blueprint",
                      "operator": "=",
                      "value": "service"
                  },
                  {
                      "property": "$identifier",
                      "operator": "=",
                      "value": "test12345"
                  }
              ]}
    print-output:
      needs: search-entity
      runs-on: ubuntu-latest
      env:
        test: ${{ needs.search-entity.outputs.entities }}
      steps:
        - name: print output
          run: echo ${{ needs.search-entity.outputs.entities }}
    
