name: testing search
on:
    workflow_dispatch:
    
jobs:
    - name: Get EKS properties
    - uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ secrets.PORT_CLIENT_ID }}
        clientSecret: ${{ secrets.PORT_CLIENT_SECRET }
        operation: SEARCH
        query: |
             {
                "combinator": "and",
                "rules": [
                {
                    "property": "$blueprint",
                    "operator": "=",
                    "value": "service"
                 },
                 {
                    "property": "$identifier",
                     "operator": "=",
                     "value": "ttest1323"
                  }
               ]
            }
